### ISSUE TITLE
Errors in 4.10.13 (tested on two boxes)

### ISSUE THREAD

**Issue by davericher** [mtompkins/linux-kernel-utilities#10]
(Reading database ... 111697 files and directories currently installed.)
Preparing to unpack linux-headers-4.10.13-041013_4.10.13-041013.201704270510_all.deb ...
Unpacking linux-headers-4.10.13-041013 (4.10.13-041013.201704270510) ...
dpkg-deb: error: unexpected end of file in archive member header in linux-headers-4.10.13-041013_4.10.13-041013.201704270510_all.deb
dpkg: error processing archive linux-headers-4.10.13-041013_4.10.13-041013.201704270510_all.deb (--install):
 subprocess dpkg-deb --fsys-tarfile returned error exit status 2
Selecting previously unselected package linux-headers-4.10.13-041013-generic.
Preparing to unpack linux-headers-4.10.13-041013-generic_4.10.13-041013.201704270510_amd64.deb ...
Unpacking linux-headers-4.10.13-041013-generic (4.10.13-041013.201704270510) ...
Preparing to unpack linux-image-4.10.13-041013-generic_4.10.13-041013.201704270510_amd64.deb ...
Done.
Unpacking linux-image-4.10.13-041013-generic (4.10.13-041013.201704270510) over (4.10.13-041013.201704270510) ...

**Comment by mtompkins** [comment]
Yep, the Ubuntu package is borked.
Not a problem with the scripts.

**Comment by davericher** [comment]
Fair enough, thanks for the quick response

**Comment by mtompkins** [comment]
Tested again today. Confirmed the packages are now good yet the updater is having a problem. Will revert. Reopening ticket.
