### ISSUE TITLE
aufs

### ISSUE THREAD

**Issue by arteniioleg** [mtompkins/linux-kernel-utilities#12]
Please add aufs support to make it work with docker.

**Comment by mtompkins** [comment]
These are just `bash` scripts that download source or pre-compiled files. There is no filesystem type support involved.

**Comment by arteniioleg** [comment]
I thought it will be easier for you to figure out what parameters and bash commands should be added to compile kernel with aufs support.
I have found some tutorials with manually applying patches but it was too advanced for me and I just reverted to stock ubuntu kernel.
Anyway, thank you for this great script. I use it sometimes to test if the latest kernel improves graphics performance in games.

**Comment by mtompkins** [comment]
I'll see if I can capture a screenshot of what you need to enable. If it is "easy" ... I'll post it here so keep an eye for a possible followup.

**Comment by mtompkins** [comment]
Have a look here: https://zackreed.me/ubuntu-14-04-with-4-0-4-kernel-and-latest-aufs-from-source/

Obviously, you'll need to consider your given version of Ubuntu and kernel. Good luck.
