### ISSUE TITLE
Is it possible to downgrade kernel?

### ISSUE THREAD

**Issue by AlbertRAR** [mtompkins/linux-kernel-utilities#3]
Hi again, @mtompkins )
Have a question. Is it possible to downgrade kernel with your script for examplae from 4.6 to 4.4?

**Comment by mtompkins** [comment]
The script isn't a part of the process.
In short you boot to the Grub menu and select a different kernel to load.
Then you can decide if you want to switch the order of booting kernels or uninstall the new one.

Have a look at youtube or such for managing your Grub loader.

**Comment by AlbertRAR** [comment]
Ok, thanks!

**Comment by mtompkins** [comment]
I wanted to clarify my response just a little:

You can compile and install any available kernel shown, including variants that are of a lower release (as in your question 4.4 < 4.6).

As for what will load on boot, Grub handles that process for you (unless you use a different bootloader). There are various ways to select which will load and that's what you should search down. Options like "last used" or by release value are all available to you.

Good luck.
