### ISSUE TITLE
Problems installing kernel on 16.04+

### ISSUE THREAD

**Issue by mordeca1** [mtompkins/linux-kernel-utilities#4]
I've tried to install kernels using your youtube video as instruction for versions of 4.8+ on ubuntu 16.04.1 LTS and always get the same errors during the final step after pre-compiled files are downloaded.

This is the install process and notice the errors:

```
Installing kernel . . .
Selecting previously unselected package linux-headers-4.8.0-040800.
(Reading database ... 208009 files and directories currently installed.)
Preparing to unpack linux-headers-4.8.0-040800_4.8.0-040800.201610022031_all.deb ...
Unpacking linux-headers-4.8.0-040800 (4.8.0-040800.201610022031) ...
Selecting previously unselected package linux-headers-4.8.0-040800-generic.
Preparing to unpack linux-headers-4.8.0-040800-generic_4.8.0-040800.201610022031_amd64.deb ...
Unpacking linux-headers-4.8.0-040800-generic (4.8.0-040800.201610022031) ...
Selecting previously unselected package linux-image-4.8.0-040800-generic.
Preparing to unpack linux-image-4.8.0-040800-generic_4.8.0-040800.201610022031_amd64.deb ...
Examining /etc/kernel/preinst.d/
run-parts: executing /etc/kernel/preinst.d/intel-microcode 4.8.0-040800-generic /boot/vmlinuz-4.8.0-040800-generic
Done.
Unpacking linux-image-4.8.0-040800-generic (4.8.0-040800.201610022031) ...
Setting up linux-headers-4.8.0-040800 (4.8.0-040800.201610022031) ...
Setting up linux-headers-4.8.0-040800-generic (4.8.0-040800.201610022031) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 4.8.0-040800-generic /boot/vmlinuz-4.8.0-040800-generic
Error! Bad return status for module build on kernel: 4.8.0-040800-generic (x86_64)
Consult /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/make.log for more information.
Setting up linux-image-4.8.0-040800-generic (4.8.0-040800.201610022031) ...
Running depmod.
update-initramfs: deferring update (hook will be called later)
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 4.8.0-040800-generic /boot/vmlinuz-4.8.0-040800-generic
run-parts: executing /etc/kernel/postinst.d/dkms 4.8.0-040800-generic /boot/vmlinuz-4.8.0-040800-generic
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/bcmwl-kernel-source.0.crash'
Error! Bad return status for module build on kernel: 4.8.0-040800-generic (x86_64)
Consult /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/make.log for more information.
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 4.8.0-040800-generic /boot/vmlinuz-4.8.0-040800-generic
update-initramfs: Generating /boot/initrd.img-4.8.0-040800-generic
run-parts: executing /etc/kernel/postinst.d/pm-utils 4.8.0-040800-generic /boot/vmlinuz-4.8.0-040800-generic
run-parts: executing /etc/kernel/postinst.d/unattended-upgrades 4.8.0-040800-generic /boot/vmlinuz-4.8.0-040800-generic
run-parts: executing /etc/kernel/postinst.d/update-notifier 4.8.0-040800-generic /boot/vmlinuz-4.8.0-040800-generic
run-parts: executing /etc/kernel/postinst.d/zz-update-grub 4.8.0-040800-generic /boot/vmlinuz-4.8.0-040800-generic
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.8.0-040800-generic
Found initrd image: /boot/initrd.img-4.8.0-040800-generic
Found linux image: /boot/vmlinuz-4.4.0-45-generic
Found initrd image: /boot/initrd.img-4.4.0-45-generic
Found linux image: /boot/vmlinuz-4.4.0-31-generic
Found initrd image: /boot/initrd.img-4.4.0-31-generic
Found Windows Boot Manager on /dev/sdc3@/EFI/Microsoft/Boot/bootmgfw.efi
Adding boot menu entry for EFI firmware configuration
done
```
My other problem is that wifi stops working completely.

Hope you can help me, I am a beginner to ubuntu.

Thank you

**Comment by mtompkins** [comment]
No worries about being "a beginner". We all start there and many of us like myself are Windows converts. I made the scripts precisely to help those adopters like yourself which is why I'd like to try and sort what is happening here.

It appears to be only one issue here, that is
- You have a Broadcom wifi device and that's the error shown when using the script ...

These two lines point to where we have to start to look:
```
Error! Bad return status for module build on kernel: 4.8.0-040800-generic (x86_64)
Consult /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/make.log for more information.
```

So in a basic sense, the scripts are working correctly. Your installation may be missing some of the files necessary for the wifi device to work on the new kernel. That happens. In Windows speak think "drivers". When you compile a new kernel (like moving from Windows 7 to 8) you need drivers for that new version.

Let's start with something simple before we get into things more complicated.
At a command prompt execute (and copy / paste results here):
`sudo apt-get install linux-generic bcmwl-kernel-source`

It's possible that's all you need.

**Comment by mordeca1** [comment]
Thanks, for replying.

I did what you asked before and after installing the kernel 4.8.6 and got the following return in terminal.

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> bcmwl-kernel-source is already the newest version (6.30.223.248+bdcom-0ubuntu8).
> The following packages were automatically installed and are no longer required:
>   linux-headers-4.4.0-31 linux-headers-4.4.0-31-generic
>   linux-image-4.4.0-31-generic linux-image-extra-4.4.0-31-generic
> Use 'sudo apt autoremove' to remove them.
> 0 upgraded, 0 newly installed, 0 to remove and 218 not upgraded.

After rebooting I got a lot of system failure notifications, so I attempted to use a backup and it completely corrupted my linux install, now I'm back to no linux install. 

Do you need to know my hardware because I'm not sure if it's hardware dependent or not.

**Comment by mtompkins** [comment]
OK - so here is where you are:

The kernel from Ubuntu that the script downloaded has not yet had the drivers from Broadcom incorporated into it. You also have the most recent release of the source files (that's what we checked). There are also others experiencing this condition on various forums which means your wifi device will not work until either:

- Ubuntu releases a kernel with those updates
- You can try and compile it yourself

It seems like you are dual booting - and if so you are likely using a Grub menu to select which OS to load? (please confirm). This is fine but does create some additional complexity. When you install a newer kernel, you should change Grub to allow you to pick the older kernel if the new one is problematic (assuming you are using Grub). This will allow you to select the original kernel and uninstall what you just added with the script.

This takes 2 trivial steps:

1. Edit the file `/etc/default/grub` as root (or with sudo) and set the **GRUB_TIMEOUT** variable to whatever you want (perhaps 10). Comment out **GRUB_HIDDEN_TIMEOUT** as shown.
2. Make the changes visible by calling `sudo update-grub`

Here's how the top of the file would look:
```
GRUB_DEFAULT="0"
#GRUB_HIDDEN_TIMEOUT="10"
GRUB_HIDDEN_TIMEOUT_QUIET="true"
GRUB_TIMEOUT="10"
GRUB_DISTRIBUTOR="`lsb_release -i -s 2> /dev/null || echo Debian`"
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX=""
```
This will give you an opportunity to manual select the kernel you would like to load. No need to reinstall from a backup or such.

Also, it appears you either manually select version 4.8.0 (or used the script's `latest` option). There have been 6 releases subsequent and you can try version 4.8.6 to see if the necessary updates have been incorporated.

Let me know if you understand the above.

I recommend:
- getting Ubuntu back into a clean state first (original 4.4.0 kernel)
- Set the Grub timeout as illustrated above
- then run the update script without `latest` and manually try kernel 4.8.6

If that doesn't solve it - you can try compiling the kernel yourself (the scripts do the hard work).
LMK

**Comment by mordeca1** [comment]
To confirm, yes I am dual booting with windows and installed the ubuntu system on the same drive as windows.
 Really glad you told me about the grub menu items as today will be the 12th time that I'm installing ubuntu and I've been pondering since yesterday if I should just give up. 

As for these steps:
I recommend:

getting Ubuntu back into a clean state first (original 4.4.0 kernel)
Set the Grub timeout as illustrated above
then run the update script without latest and manually try kernel 4.8.6

I've actually done exactly this for a couple days straight before contacting you. I've tried installing versions 4.8, 4.8.5, 4.8.6 multiple times and tried different guides but yours was recommended on ubuntuforums (plus the youtube video made it easier).

After the above 3 steps are done, I always end up with errors as seen in my first post.

**Comment by mtompkins** [comment]
In respect to dual-booting ...

I would recommend abandoning that unless absolutely necessary and consider running Virtualbox. Then install Ubuntu within Vbox. This will allow you to take snapshots, make any / all changes to Ubu with the ability to immediate rollback to a previous state. And of course, you don't risk mangling the Window install / boot. It should also remove the networking (wifi) issue. The experience of Ubuntu via VBox is really quite close to a pure install. You'll get the Ubuntu experience with some safety until you are a bit more familiar with it all. 

That said, based on your last update and down the dual-boot path the next step is to try and compile yourself. I've tried to make it equally easy ...

Get Ubuntu into a clean state and use the `compile_linux_kernel.sh` script. There's a video referenced on the main page you can have a look at to have some expectation of what will happen.

**Comment by mtompkins** [comment]
If convenient (and you are in the dual-boot fashion), before trying an upgrade or kernel compile please give me the result of this command:

`lspci -nn -d 14e4:`
