### ISSUE TITLE
Adding bcmwl-kernel-source kills WiFi on Dell XPS 15 9550

### ISSUE THREAD

**Issue by nknganda** [mtompkins/linux-kernel-utilities#5]
Hi,

Adding bcmwl-kernel-source kills WiFi on Dell XPS 15 9550

* OS: Ubuntu 16.04

**Comment by mtompkins** [comment]
Thnx - I have to improve the Broadcom detection. I'll revert the change in the interim.

**Comment by mtompkins** [comment]
Reverted
