### ISSUE TITLE
How to update to specific kernel version?

### ISSUE THREAD

**Issue by stepanzarubin** [mtompkins/linux-kernel-utilities#8]

**Comment by mtompkins** [comment]
You are presented with a menu to select a kernel version in both the compiling and updating scripts.
Have a look at the videos if you need a reference.

**Comment by stepanzarubin** [comment]
I have not found how to update to specific version, both README and video shows only how to update to latest kernel.
Thanks.

**Comment by mtompkins** [comment]
As per the README.md:

> Precompiled Ubuntu (and derivatives)
>To download and install a precompiled Ubuntu kernel from kernel.ubuntu.com

`./update_ubuntu_kernel.sh`

Just use that and the menu will be presented. I did forget the videos showed the automation.
Just run the script with no other parameters.

**Comment by stepanzarubin** [comment]
Thanks! 👍

**Comment by mtompkins** [comment]
You're welcome - hope you enjoy the scripts.

**Comment by stepanzarubin** [comment]
By the way, you donation option via PayPal will not work for many people outside US or those not using PayPal. I have seen more universal options.

**Comment by mtompkins** [comment]
Thank you for that - I appreciate it. To date, no-one has (to my knowledge) even made an attempt at a small "gift". I figure anyone can do an Amazon gift card from anyone on the planet if they want to and that is gladly accepted.
